from enum import Enum


class Status(str, Enum):
    OK = "OK"
    NO_PDF = "NO_PDF"
    MULTIPLE_PDFS = "MULTIPLE_PDFS"
    BROKEN_ATTACHMENT_PATH = "BROKEN_ATTACHMENT_PATH"
    NO_NOTION_MATCH = "NO_NOTION_MATCH"
    MULTIPLE_NOTION_MATCHES = "MULTIPLE_NOTION_MATCHES"
    NOTION_SCHEMA_ERROR = "NOTION_SCHEMA_ERROR"
    NOTION_AUTH_ERROR = "NOTION_AUTH_ERROR"
    NOTION_RATE_LIMIT = "NOTION_RATE_LIMIT"
    NOTION_NETWORK_ERROR = "NOTION_NETWORK_ERROR"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    UPLOAD_FAILED = "UPLOAD_FAILED"
    ATTACH_FAILED = "ATTACH_FAILED"
    STATE_SAVE_FAILED = "STATE_SAVE_FAILED"
    UNCHANGED = "UNCHANGED"
    SKIPPED_AMBIGUOUS = "SKIPPED_AMBIGUOUS"
